# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
stages:
  - make_deb
image: 192.168.12.16:5000/sunny-ctirobot/cti_ade_base_humble:latest

.tags: &tag
  - humble
.before_script:
  before_script:
    - echo "deb http://192.168.100.48:8081/repository/apt/ focal main" | tee  /etc/apt/sources.list.d/ctirobot.list
    - wget -qO -  http://192.168.100.24/public.gpg.key  | apt-key add -
    - apt update -y
    - '
      #  apt install -y  ros-humble-cti-rblite
      '

make_deb:
  tags:
    - humble
  stage: make_deb
  extends: .before_script
  script:
    - rosdep update
    - sed -i 's/my $ignore_missing_info = 0;/my $ignore_missing_info = 1;/g' /usr/bin/dpkg-shlibdeps
    - bash .make_deb.sh
    - mv ../*.deb . && mv ../*.ddeb .
    - bash .upload.sh
  only:
    - humble
  artifacts:
    paths:
      - "*.deb"
    expire_in: 1 week
